build:
  mkdir -p build
  poetry export --without-hashes -f requirements.txt > build/requirements.txt
  docker build -t wooya/dataprep-profiling -f docker/Dockerfile .

bench to="/dev/null":
  python profiling.py | tee -a {{to}}

docker:
  docker run -it --rm -v$PWD:/workdir/profiling -v$PWD/../dataprep:/workdir/dataprep -v$PWD/data:/workdir/data -p8889:8888 --network dsl wooya/dataprep-profiling bash