name: Performance Benchmarks

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  benchmark:
    name: ${{ matrix.os }} x ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest]
        python: ['3.7.9']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Run benchmark
        run: |
          pip install poetry
          poetry install
      - run: pytest tests/benchmarks/eda.py --benchmark-json benchmark.json
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: DataPrep.EDA Benchmarks
          tool: 'pytest'
          output-file-path: benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          comment-always: true