name: Clean GUI CI

on:
  push:
    branches: 
      - develop
      - master
  pull_request:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies & Build Frontend
      run: |
        cd dataprep/clean/gui/clean_frontend
        rm -rf node_modules package-lock.json
        npm install
        npm run build
