on: pull_request
name: Run Impacted Tests
jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r .github/requirements.txt
  
    - name: Install dependencies
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.0
        poetry_version: 0.12.17
        args: install

    - name: Run tests
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo $FILES
        chmod +x .github/runTests.sh
        .github/runTests.sh "$FILES"
    
  
        
 
   
